### ISSUE TITLE
Problem untersuchen, das nur auf Hoststar auftritt

### ISSUE THREAD

**Issue by olzimmerberg** [olzimmerberg/olz-website#186]
- Das Problem tritt lokal nicht auf
- Das Problem trat für Screenshots nicht auf
- Das Problem wurde mit require RoleRepository gelöst
```
[Fri Aug 21 08:50:20.729505 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: PHP Fata
[Fri Aug 21 08:50:20.729689 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: l error:  Uncaught Error: Class 'RoleRepository' not found in /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php:69
[Fri Aug 21 08:50:20.729700 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: Stack trace:
[Fri Aug 21 08:50:20.729705 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: #0 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(51): Doctrine\\ORM\\Repository\\DefaultRepositoryFactory->createRepository(Object(Doctrine\\ORM\\EntityManager), 'Role')
[Fri Aug 21 08:50:20.729712 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: #1 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(738): Doctrine\\ORM\\Repository\\DefaultRepositoryFactory->getRepository(Object(Doctrine\\ORM\\EntityManager), 'Role')
[Fri Aug 21 08:50:20.729719 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: #2 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/fuer_einsteiger_r.php(11): Doctrine\\ORM\\EntityManager->getRepository('Role')
[Fri Aug 21 08:50:20.729734 2020] [fcgid:warn] [pid 9295] [client 93.158.161.4:34306] mod_fcgid: stderr: #3 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/fuer_einsteiger.php(7): include('/hom in /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php on line 69
[Fri Aug 21 08:51:21.066087 2020] [fcgid:warn] [pid 8695] [client 34.78.140.88:35296] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Class 'RoleRepository' not found in /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php:69, referer: https://olzimmerberg.ch/_/index.php?page=8
[Fri Aug 21 08:51:21.066111 2020] [fcgid:warn] [pid 8695] [client 34.78.140.88:35296] mod_fcgid: stderr: Stack trace:, referer: https://olzimmerberg.ch/_/index.php?page=8
[Fri Aug 21 08:51:21.066115 2020] [fcgid:warn] [pid 8695] [client 34.78.140.88:35296] mod_fcgid: stderr: #0 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php(51): Doctrine\\ORM\\Repository\\DefaultRepositoryFactory->createRepository(Object(Doctrine\\ORM\\EntityManager), 'Role'), referer: https://olzimmerberg.ch/_/index.php?page=8
[Fri Aug 21 08:51:21.066118 2020] [fcgid:warn] [pid 8695] [client 34.78.140.88:35296] mod_fcgid: stderr: #1 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(738): Doctrine\\ORM\\Repository\\DefaultRepositoryFactory->getRepository(Object(Doctrine\\ORM\\EntityManager), 'Role'), referer: https://olzimmerberg.ch/_/index.php?page=8
[Fri Aug 21 08:51:21.066121 2020] [fcgid:warn] [pid 8695] [client 34.78.140.88:35296] mod_fcgid: stderr: #2 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/kontakt_d.php(51): Doctrine\\ORM\\EntityManager->getRepository('Role'), referer: https://olzimmerberg.ch/_/index.php?page=8
[Fri Aug 21 08:51:21.066124 2020] [fcgid:warn] [pid 8695] [client 34.78.140.88:35296] mod_fcgid: stderr: #3 /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/kontakt.php(6): include('/home/ch279178/...') in /home/ch279178/web/olzimmerberg.ch/public_html/deploy/2020-08-18_00_20_48/config/vendor/doctrine/orm/lib/Doctrine/ORM/Repository/DefaultRepositoryFactory.php on line 69, referer: https://olzimmerberg.ch/_/index.php?page=8
```

=> Warum tritt das Problem auf Hoststar auf?
=> Warum nicht in den Screenshots?

**Comment by allestuetsmerweh** [comment]
Das Problem wird mit Symfony & Namespaces & PHP 8.x ziemlich sicher behoben sein!
